kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
